# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
    config.vm.define "SRX01" do |srx01|
        srx01.ssh.insert_key = false
        srx01.vm.box = 'juniper/ffp-12.1X47-D15.4-packetmode'
        # DO NOT REMOVE / NO VMtools installed
        srx01.vm.synced_folder '.', '/vagrant', disabled: true
    end
end